eureka:
    client:
        registryFetchIntervalSeconds: 1
        leaseRenewalIntervalInSeconds: 1
        eureka-server-u-r-l-context: http://localhost:8761/eureka
    instance:
        hostname: localhost
        metadata-map:
            version: new
feign:
    hystrix:
        enabled: false

ribbon:
    eager-load:
        enabled: true
    ConnectTimeout: 1000
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1



server:
    port: 8099
spring:
    application:
        name: order-service
